'use strict';

var PlayerActionType = {
  INITIALIZED: 'PLAYER_INITIALIZED',
  UPDATED: 'PLAYER_UPDATED',

  LOGIN: 'PLAYER_LOGIN',
  LOGIN_SUCCESS: 'PLAYER_LOGIN_SUCCESS',
  LOGIN_ERROR: 'PLAYER_LOGIN_ERROR'
};

module.exports = PlayerActionType;
